baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Naïm Gómez Cano cv"
    author = "Naïm Gómez Cano"
    description = "Currículum Vitae"
    copyright = ""

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Naïm Gómez Cano"
		tagline = ""
		location = "Barcelona, España"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "#"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-stack-overflow"
            url = "#"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "#"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "#"
            title = "Twitter"
		[[params.social.list]]
            class = "ai"
            icon = "ai-google-scholar"
            url = "#"
            title = "Google Scholar"
		[[params.social.list]]
            class = "ai"
            icon = "ai-researchgate"
            url = "#"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "Sobre Mí"
        icon = "fas fa-user"
        description = "**Soy estudiante de sistemas microinformáticos y redes.** En un futuro me gustaría enfocar mi carrera profesional en el **sector de la programación**, me considero una persona autodidacta disfruto de aprender cosas nuevas y estar informado de las nuevas tecnologías."

    # Education section
    [params.education]
        title = "Educación"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Sistemas Microinformáticos y Redes"
            college = "IES Joan d'Austria"
            dates = "2019 - Actualidad"
        
        [[params.education.list]]
            degree = "Educación Secundaria Obligatoria"
            college = "FEDAC Sant Feliu de Codines"
            dates = "2015 - 2019"

      type = "Proceedings"

    # Project section
    [params.project]
        title = "Proyectos"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "punteros multinivel de cheat engine a c++"
            url = "https://github.com/NgomezKS/Multilevel-Pointers-CE-to-Cpp"
            description = "Es una pequeña biblioteca que ofrece una manera fácil de escribir y leer punteros multinivel en c++ encontrados en cheat engine."
        [[params.project.list]]
            title = "inteligencia artificial básica para x-plane11"
            url = "https://github.com/NgomezKS/Basic-AI-for-X-Plane11"
            description = "Es una pequeña artificial programada en c++ que tiene capacidad de despegar aviones bimotor, ascender,  mantener una altitud seleccionada, seguir y mantener un rumbo."         

    # Skill section
    [params.skill]
        title = "Habilidades"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Blender"
            skillrating = 70
        [[params.skill.list]]
            skill = "c++"
            skillrating = 60
        [[params.skill.list]]
            skill = "Premier Pro 2017"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "jugar a videojuegos"
        [[params.hobby.list]]		
		    hobby = "programar"
        [[params.hobby.list]]		
		    hobby = "salir con la bicicleta"